export { Navbar } from './navbar'
export { Hero } from './hero'
export { FeaturesBento } from './features-bento'
export { HowItWorks } from './how-it-works'
export { FAQs } from './faqs'
export { CTA } from './cta'
export { Footer } from './footer'
